#install.packages("devtools")
library(devtools)
devtools::install_github("notllikethat/ChemmineR")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("BioNet")
install.packages("data.table")
install.packages("tidyverse")
install.packages("igraph")
